databases:
  - name: quote_editor
    databaseName: quote_editor_production
    user: quote_editor
    region: ohio
    plan: starter

services:
  - type: web
    name: quote_editor
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    region: ohio
    autoDeploy: false
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quote_editor
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: quote_editor_redis
          property: connectionString
  - type: worker
    name: quote_editor_sidekiq_worker
    region: ohio
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    autoDeploy: false
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: quote_editor_redis
          property: connectionString

  - type: redis
    name: quote_editor_redis
    region: ohio
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
